services :
  mariadb :
    build:
      context: ./requirements/mariadb
      dockerfile : Dockerfile

    image : mariadb
    container_name : mariadb
    restart: always
    env_file:
      - .env
    secrets :
      - db_root_password
      - db_password
    volumes :
      - mariadb_data:/var/lib/mysql
    networks :
      - inception

    wordpress:
      build :
        context : ./requirements/wordpress
        dockerfile: Dockerfile
      image: wordpress
      restart: always
      env_file:
        - .env
      secrets:
        - db_password
      volumes:
        - wordi

      networks :
        - inception

      depends_on:
        - mariadb

  ngnix:
    build:
      context : ./requirments/ngnix
      dockerfile: Dockerfile
    image : ngnix
    container_name: ngnix
    restart : always
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html:ro
    networks:
      - inception
    depends on:
      - wordpress

   volumes:

     mariadb_data:
       driver : local
       driver_opts :
         type: none
         o: bind
         device: /home/sadeen/data/mariadb

    wordpress_data:
      driver: local
      driver_opts: 
          type: none
          o: bind
          device : /home/sadeen/data/wordpress

    networks:
      inception:
        driver: bridge
    secrets:
      db_root_password:
        file:../secrets/db_root_password.txt
      db_password:
        file:../secrets/db_password.txt


