From debian:12

RUN apt-get update && \
    apt-get install -y  mariadb-server mariadb-client && \
    rm -rf /var//lib/apt/lists/*

RUN mkdir -p /run/mysql && \
    chown -R mysql:mysql /run/mysql && \
    chown -R  mysql:mysql /var/lib/mysql 

COPY tools/int-db.sh /usr/local/bin/init-db.sh

RUN chmod +x /usr/local/bin//init-db.sh

EXPOSE 3306 # how we know the correct port


ENTRYPOINT ["/usr/local/bin/init-db.sh"]

CMD ["mariadbd", "--user=mysql", "--bind-address=0.0.0.0"]
