FROM debian:12

RUN apt-get update && \
    apt-get install -y mariadb-server && \
    rm -rf /var/lib/apt/lists/*

COPY conf/50-server.cnf /etc/mysql/mariadb.conf.d/50-server.cnf

COPY tools/mariadb-init.sh /usr/local/bin/mariadb-init.sh

RUN chmod +x /usr/local/bin/mariadb-init.sh

ENTRYPOINT ["/usr/local/bin/mariadb-init.sh"]
